#后台端口号
server:
  port: 8086

#Spring相关配置
spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
#    password: dfasufoufdji13148209jklda!@@#
  servlet:
    multipart: #设置上传文件大小
      enabled: true
      max-file-size: 2MB #设置单个文件的大小
      max-request-size: 2MB #设置单次请求的文件的总大小
  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: full

#MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:com/test/recipe/mapper/mapping/*.xml
  type-aliases-package: com.test.recipe.*

#上传文件配置
file:
  #映射路径
  path: upload/**
  #真实路径中文件夹名
  address: /upload/